// <auto-generated />
using System;
using MediCoreHospital.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediCoreHospital.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0-rc.1.25451.107");

            modelBuilder.Entity("MediCoreHospital.Models.Admission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("BedNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DischargeDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ward")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Admissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdmissionDate = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 9,
                            DoctorId = 48,
                            PatientId = 60,
                            Status = 1,
                            Ward = 2
                        },
                        new
                        {
                            Id = 2,
                            AdmissionDate = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 14,
                            DoctorId = 1,
                            PatientId = 26,
                            Status = 1,
                            Ward = 3
                        },
                        new
                        {
                            Id = 3,
                            AdmissionDate = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 5,
                            DischargeDate = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 25,
                            PatientId = 14,
                            Status = 2,
                            Ward = 3
                        },
                        new
                        {
                            Id = 4,
                            AdmissionDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 5,
                            DoctorId = 48,
                            PatientId = 22,
                            Status = 1,
                            Ward = 3
                        },
                        new
                        {
                            Id = 5,
                            AdmissionDate = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 7,
                            DoctorId = 36,
                            PatientId = 60,
                            Status = 1,
                            Ward = 3
                        },
                        new
                        {
                            Id = 6,
                            AdmissionDate = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 18,
                            DischargeDate = new DateTime(2026, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 40,
                            PatientId = 98,
                            Status = 2,
                            Ward = 4
                        },
                        new
                        {
                            Id = 7,
                            AdmissionDate = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 12,
                            DoctorId = 27,
                            PatientId = 26,
                            Status = 1,
                            Ward = 2
                        },
                        new
                        {
                            Id = 8,
                            AdmissionDate = new DateTime(2026, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 18,
                            DoctorId = 23,
                            PatientId = 58,
                            Status = 1,
                            Ward = 3
                        },
                        new
                        {
                            Id = 9,
                            AdmissionDate = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 4,
                            DischargeDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 23,
                            PatientId = 60,
                            Status = 2,
                            Ward = 1
                        },
                        new
                        {
                            Id = 10,
                            AdmissionDate = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 19,
                            DoctorId = 43,
                            PatientId = 97,
                            Status = 1,
                            Ward = 1
                        },
                        new
                        {
                            Id = 11,
                            AdmissionDate = new DateTime(2026, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 5,
                            DoctorId = 40,
                            PatientId = 11,
                            Status = 1,
                            Ward = 1
                        },
                        new
                        {
                            Id = 12,
                            AdmissionDate = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 5,
                            DischargeDate = new DateTime(2026, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 9,
                            PatientId = 14,
                            Status = 2,
                            Ward = 2
                        },
                        new
                        {
                            Id = 13,
                            AdmissionDate = new DateTime(2026, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 1,
                            DoctorId = 2,
                            PatientId = 85,
                            Status = 1,
                            Ward = 1
                        },
                        new
                        {
                            Id = 14,
                            AdmissionDate = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 10,
                            DoctorId = 17,
                            PatientId = 77,
                            Status = 1,
                            Ward = 3
                        },
                        new
                        {
                            Id = 15,
                            AdmissionDate = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 5,
                            DischargeDate = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 33,
                            PatientId = 33,
                            Status = 2,
                            Ward = 4
                        },
                        new
                        {
                            Id = 16,
                            AdmissionDate = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 19,
                            DoctorId = 23,
                            PatientId = 24,
                            Status = 1,
                            Ward = 4
                        },
                        new
                        {
                            Id = 17,
                            AdmissionDate = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 14,
                            DoctorId = 16,
                            PatientId = 21,
                            Status = 1,
                            Ward = 1
                        },
                        new
                        {
                            Id = 18,
                            AdmissionDate = new DateTime(2026, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 6,
                            DischargeDate = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 40,
                            PatientId = 38,
                            Status = 2,
                            Ward = 2
                        },
                        new
                        {
                            Id = 19,
                            AdmissionDate = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 2,
                            DoctorId = 41,
                            PatientId = 33,
                            Status = 1,
                            Ward = 3
                        },
                        new
                        {
                            Id = 20,
                            AdmissionDate = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 11,
                            DoctorId = 28,
                            PatientId = 27,
                            Status = 1,
                            Ward = 1
                        },
                        new
                        {
                            Id = 21,
                            AdmissionDate = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 3,
                            DischargeDate = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 47,
                            PatientId = 47,
                            Status = 2,
                            Ward = 4
                        },
                        new
                        {
                            Id = 22,
                            AdmissionDate = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 16,
                            DoctorId = 49,
                            PatientId = 95,
                            Status = 1,
                            Ward = 4
                        },
                        new
                        {
                            Id = 23,
                            AdmissionDate = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 14,
                            DoctorId = 4,
                            PatientId = 77,
                            Status = 1,
                            Ward = 3
                        },
                        new
                        {
                            Id = 24,
                            AdmissionDate = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 11,
                            DischargeDate = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 37,
                            PatientId = 31,
                            Status = 2,
                            Ward = 2
                        },
                        new
                        {
                            Id = 25,
                            AdmissionDate = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 4,
                            DoctorId = 32,
                            PatientId = 48,
                            Status = 1,
                            Ward = 2
                        },
                        new
                        {
                            Id = 26,
                            AdmissionDate = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 18,
                            DoctorId = 12,
                            PatientId = 52,
                            Status = 1,
                            Ward = 4
                        },
                        new
                        {
                            Id = 27,
                            AdmissionDate = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 8,
                            DischargeDate = new DateTime(2026, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 8,
                            PatientId = 45,
                            Status = 2,
                            Ward = 3
                        },
                        new
                        {
                            Id = 28,
                            AdmissionDate = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 10,
                            DoctorId = 20,
                            PatientId = 25,
                            Status = 1,
                            Ward = 4
                        },
                        new
                        {
                            Id = 29,
                            AdmissionDate = new DateTime(2026, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 15,
                            DoctorId = 15,
                            PatientId = 57,
                            Status = 1,
                            Ward = 3
                        },
                        new
                        {
                            Id = 30,
                            AdmissionDate = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 16,
                            DischargeDate = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 43,
                            PatientId = 37,
                            Status = 2,
                            Ward = 4
                        },
                        new
                        {
                            Id = 31,
                            AdmissionDate = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 4,
                            DoctorId = 13,
                            PatientId = 38,
                            Status = 1,
                            Ward = 2
                        },
                        new
                        {
                            Id = 32,
                            AdmissionDate = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 14,
                            DoctorId = 18,
                            PatientId = 82,
                            Status = 1,
                            Ward = 2
                        },
                        new
                        {
                            Id = 33,
                            AdmissionDate = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 18,
                            DischargeDate = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 40,
                            PatientId = 91,
                            Status = 2,
                            Ward = 2
                        },
                        new
                        {
                            Id = 34,
                            AdmissionDate = new DateTime(2026, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 1,
                            DoctorId = 36,
                            PatientId = 72,
                            Status = 1,
                            Ward = 2
                        },
                        new
                        {
                            Id = 35,
                            AdmissionDate = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 7,
                            DoctorId = 44,
                            PatientId = 72,
                            Status = 1,
                            Ward = 4
                        },
                        new
                        {
                            Id = 36,
                            AdmissionDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 8,
                            DischargeDate = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 34,
                            PatientId = 45,
                            Status = 2,
                            Ward = 1
                        },
                        new
                        {
                            Id = 37,
                            AdmissionDate = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 10,
                            DoctorId = 23,
                            PatientId = 82,
                            Status = 1,
                            Ward = 4
                        },
                        new
                        {
                            Id = 38,
                            AdmissionDate = new DateTime(2026, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 1,
                            DoctorId = 38,
                            PatientId = 21,
                            Status = 1,
                            Ward = 2
                        },
                        new
                        {
                            Id = 39,
                            AdmissionDate = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 10,
                            DischargeDate = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 20,
                            PatientId = 75,
                            Status = 2,
                            Ward = 3
                        },
                        new
                        {
                            Id = 40,
                            AdmissionDate = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 5,
                            DoctorId = 3,
                            PatientId = 6,
                            Status = 1,
                            Ward = 1
                        },
                        new
                        {
                            Id = 41,
                            AdmissionDate = new DateTime(2026, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 8,
                            DoctorId = 16,
                            PatientId = 81,
                            Status = 1,
                            Ward = 3
                        },
                        new
                        {
                            Id = 42,
                            AdmissionDate = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 13,
                            DischargeDate = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 5,
                            PatientId = 83,
                            Status = 2,
                            Ward = 2
                        },
                        new
                        {
                            Id = 43,
                            AdmissionDate = new DateTime(2026, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 17,
                            DoctorId = 41,
                            PatientId = 95,
                            Status = 1,
                            Ward = 4
                        },
                        new
                        {
                            Id = 44,
                            AdmissionDate = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 19,
                            DoctorId = 19,
                            PatientId = 42,
                            Status = 1,
                            Ward = 3
                        },
                        new
                        {
                            Id = 45,
                            AdmissionDate = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 9,
                            DischargeDate = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 14,
                            PatientId = 98,
                            Status = 2,
                            Ward = 4
                        },
                        new
                        {
                            Id = 46,
                            AdmissionDate = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 3,
                            DoctorId = 31,
                            PatientId = 50,
                            Status = 1,
                            Ward = 3
                        },
                        new
                        {
                            Id = 47,
                            AdmissionDate = new DateTime(2026, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 3,
                            DoctorId = 38,
                            PatientId = 78,
                            Status = 1,
                            Ward = 1
                        },
                        new
                        {
                            Id = 48,
                            AdmissionDate = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 13,
                            DischargeDate = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 21,
                            PatientId = 12,
                            Status = 2,
                            Ward = 2
                        },
                        new
                        {
                            Id = 49,
                            AdmissionDate = new DateTime(2026, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 16,
                            DoctorId = 20,
                            PatientId = 14,
                            Status = 1,
                            Ward = 2
                        },
                        new
                        {
                            Id = 50,
                            AdmissionDate = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 13,
                            DoctorId = 35,
                            PatientId = 39,
                            Status = 1,
                            Ward = 3
                        },
                        new
                        {
                            Id = 51,
                            AdmissionDate = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 1,
                            DischargeDate = new DateTime(2026, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 15,
                            PatientId = 28,
                            Status = 2,
                            Ward = 4
                        },
                        new
                        {
                            Id = 52,
                            AdmissionDate = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 15,
                            DoctorId = 50,
                            PatientId = 28,
                            Status = 1,
                            Ward = 3
                        },
                        new
                        {
                            Id = 53,
                            AdmissionDate = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 2,
                            DoctorId = 5,
                            PatientId = 18,
                            Status = 1,
                            Ward = 1
                        },
                        new
                        {
                            Id = 54,
                            AdmissionDate = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 19,
                            DischargeDate = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            PatientId = 75,
                            Status = 2,
                            Ward = 2
                        },
                        new
                        {
                            Id = 55,
                            AdmissionDate = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 11,
                            DoctorId = 32,
                            PatientId = 99,
                            Status = 1,
                            Ward = 1
                        },
                        new
                        {
                            Id = 56,
                            AdmissionDate = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 18,
                            DoctorId = 18,
                            PatientId = 43,
                            Status = 1,
                            Ward = 1
                        },
                        new
                        {
                            Id = 57,
                            AdmissionDate = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 9,
                            DischargeDate = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 32,
                            PatientId = 44,
                            Status = 2,
                            Ward = 2
                        },
                        new
                        {
                            Id = 58,
                            AdmissionDate = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 8,
                            DoctorId = 11,
                            PatientId = 45,
                            Status = 1,
                            Ward = 1
                        },
                        new
                        {
                            Id = 59,
                            AdmissionDate = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 6,
                            DoctorId = 15,
                            PatientId = 31,
                            Status = 1,
                            Ward = 4
                        },
                        new
                        {
                            Id = 60,
                            AdmissionDate = new DateTime(2026, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BedNumber = 14,
                            DischargeDate = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 27,
                            PatientId = 77,
                            Status = 2,
                            Ward = 3
                        });
                });

            modelBuilder.Entity("MediCoreHospital.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("MediCoreHospital.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignedWard")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedWard = 1,
                            FullName = "Dr. Ali Khan",
                            IsAvailable = true,
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = 2,
                            AssignedWard = 2,
                            FullName = "Dr. Fatima Rahman",
                            IsAvailable = true,
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = 3,
                            AssignedWard = 2,
                            FullName = "Dr. Tariq Mahmood",
                            IsAvailable = true,
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = 4,
                            AssignedWard = 1,
                            FullName = "Dr. Aisha Siddiqui",
                            IsAvailable = true,
                            Specialization = "General Medicine"
                        },
                        new
                        {
                            Id = 5,
                            AssignedWard = 2,
                            FullName = "Dr. Omar Farooq",
                            IsAvailable = true,
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = 6,
                            AssignedWard = 2,
                            FullName = "Dr. Zainab Malik",
                            IsAvailable = true,
                            Specialization = "General Medicine"
                        },
                        new
                        {
                            Id = 7,
                            AssignedWard = 2,
                            FullName = "Dr. Muhammad Iqbal",
                            IsAvailable = true,
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = 8,
                            AssignedWard = 4,
                            FullName = "Dr. Sana Qureshi",
                            IsAvailable = true,
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = 9,
                            AssignedWard = 4,
                            FullName = "Dr. Bilal Ahmed",
                            IsAvailable = true,
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = 10,
                            AssignedWard = 2,
                            FullName = "Dr. Maryam Shah",
                            IsAvailable = false,
                            Specialization = "General Medicine"
                        },
                        new
                        {
                            Id = 11,
                            AssignedWard = 1,
                            FullName = "Dr. Hasan Raza",
                            IsAvailable = false,
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = 12,
                            AssignedWard = 1,
                            FullName = "Dr. Hira Tariq",
                            IsAvailable = false,
                            Specialization = "General Medicine"
                        },
                        new
                        {
                            Id = 13,
                            AssignedWard = 4,
                            FullName = "Dr. Usman Khalid",
                            IsAvailable = true,
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = 14,
                            AssignedWard = 3,
                            FullName = "Dr. Nadia Hussain",
                            IsAvailable = true,
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = 15,
                            AssignedWard = 2,
                            FullName = "Dr. Salman Sheikh",
                            IsAvailable = false,
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = 16,
                            AssignedWard = 4,
                            FullName = "Dr. Zara Abbas",
                            IsAvailable = false,
                            Specialization = "General Medicine"
                        },
                        new
                        {
                            Id = 17,
                            AssignedWard = 3,
                            FullName = "Dr. Ibrahim Syed",
                            IsAvailable = true,
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = 18,
                            AssignedWard = 3,
                            FullName = "Dr. Huda Al-Farsi",
                            IsAvailable = true,
                            Specialization = "General Medicine"
                        },
                        new
                        {
                            Id = 19,
                            AssignedWard = 4,
                            FullName = "Dr. Yusuf Mansour",
                            IsAvailable = true,
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = 20,
                            AssignedWard = 4,
                            FullName = "Dr. Amina Begum",
                            IsAvailable = true,
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = 21,
                            AssignedWard = 4,
                            FullName = "Dr. Hamza Bukhari",
                            IsAvailable = true,
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = 22,
                            AssignedWard = 1,
                            FullName = "Dr. Rabia Hassan",
                            IsAvailable = true,
                            Specialization = "General Medicine"
                        },
                        new
                        {
                            Id = 23,
                            AssignedWard = 3,
                            FullName = "Dr. Khalid Mustafa",
                            IsAvailable = true,
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = 24,
                            AssignedWard = 2,
                            FullName = "Dr. Nida Anwar",
                            IsAvailable = false,
                            Specialization = "General Medicine"
                        },
                        new
                        {
                            Id = 25,
                            AssignedWard = 2,
                            FullName = "Dr. Zaid Jamil",
                            IsAvailable = true,
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = 26,
                            AssignedWard = 1,
                            FullName = "Dr. Farah Hashmi",
                            IsAvailable = true,
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = 27,
                            AssignedWard = 1,
                            FullName = "Dr. Imran Qazi",
                            IsAvailable = true,
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = 28,
                            AssignedWard = 1,
                            FullName = "Dr. Sadia Rizvi",
                            IsAvailable = false,
                            Specialization = "General Medicine"
                        },
                        new
                        {
                            Id = 29,
                            AssignedWard = 3,
                            FullName = "Dr. Faisal Baig",
                            IsAvailable = false,
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = 30,
                            AssignedWard = 3,
                            FullName = "Dr. Yasmin Javed",
                            IsAvailable = false,
                            Specialization = "General Medicine"
                        },
                        new
                        {
                            Id = 31,
                            AssignedWard = 4,
                            FullName = "Dr. Saad Ansari",
                            IsAvailable = false,
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = 32,
                            AssignedWard = 2,
                            FullName = "Dr. Saima Latif",
                            IsAvailable = false,
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = 33,
                            AssignedWard = 2,
                            FullName = "Dr. Tariq Najeeb",
                            IsAvailable = false,
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = 34,
                            AssignedWard = 2,
                            FullName = "Dr. Ayesha Gilani",
                            IsAvailable = true,
                            Specialization = "General Medicine"
                        },
                        new
                        {
                            Id = 35,
                            AssignedWard = 1,
                            FullName = "Dr. Rashid Dar",
                            IsAvailable = true,
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = 36,
                            AssignedWard = 4,
                            FullName = "Dr. Samira Khan",
                            IsAvailable = true,
                            Specialization = "General Medicine"
                        },
                        new
                        {
                            Id = 37,
                            AssignedWard = 3,
                            FullName = "Dr. Nabil Farooq",
                            IsAvailable = false,
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = 38,
                            AssignedWard = 2,
                            FullName = "Dr. Uzma Aslam",
                            IsAvailable = true,
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = 39,
                            AssignedWard = 1,
                            FullName = "Dr. Kamal Haider",
                            IsAvailable = true,
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = 40,
                            AssignedWard = 3,
                            FullName = "Dr. Sanaullah Shah",
                            IsAvailable = false,
                            Specialization = "General Medicine"
                        },
                        new
                        {
                            Id = 41,
                            AssignedWard = 4,
                            FullName = "Dr. Asma Chohan",
                            IsAvailable = true,
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = 42,
                            AssignedWard = 3,
                            FullName = "Dr. Jamaluddin",
                            IsAvailable = false,
                            Specialization = "General Medicine"
                        },
                        new
                        {
                            Id = 43,
                            AssignedWard = 1,
                            FullName = "Dr. Shazia Mian",
                            IsAvailable = true,
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = 44,
                            AssignedWard = 4,
                            FullName = "Dr. Rafiq Zaman",
                            IsAvailable = true,
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = 45,
                            AssignedWard = 2,
                            FullName = "Dr. Mehwish Akram",
                            IsAvailable = true,
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = 46,
                            AssignedWard = 2,
                            FullName = "Dr. Jamil Khattak",
                            IsAvailable = true,
                            Specialization = "General Medicine"
                        },
                        new
                        {
                            Id = 47,
                            AssignedWard = 4,
                            FullName = "Dr. Ghazala Pervez",
                            IsAvailable = true,
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = 48,
                            AssignedWard = 2,
                            FullName = "Dr. Waqar Younis",
                            IsAvailable = true,
                            Specialization = "General Medicine"
                        },
                        new
                        {
                            Id = 49,
                            AssignedWard = 2,
                            FullName = "Dr. Bushra Iqbal",
                            IsAvailable = true,
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = 50,
                            AssignedWard = 2,
                            FullName = "Dr. Qasim Zia",
                            IsAvailable = true,
                            Specialization = "Cardiology"
                        });
                });

            modelBuilder.Entity("MediCoreHospital.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicalHistory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 14,
                            ContactNumber = "0300-5076949",
                            FullName = "Ammad",
                            Gender = "Male",
                            MedicalHistory = "History of condition 2"
                        },
                        new
                        {
                            Id = 2,
                            Age = 19,
                            ContactNumber = "0300-6595096",
                            FullName = "Ahmed",
                            Gender = "Male",
                            MedicalHistory = "History of condition 3"
                        },
                        new
                        {
                            Id = 3,
                            Age = 71,
                            ContactNumber = "0300-4246226",
                            FullName = "Ali",
                            Gender = "Male",
                            MedicalHistory = "History of condition 4"
                        },
                        new
                        {
                            Id = 4,
                            Age = 19,
                            ContactNumber = "0300-7096827",
                            FullName = "Omar",
                            Gender = "Male",
                            MedicalHistory = "History of condition 5"
                        },
                        new
                        {
                            Id = 5,
                            Age = 21,
                            ContactNumber = "0300-2121479",
                            FullName = "Tariq",
                            Gender = "Male",
                            MedicalHistory = "History of condition 6"
                        },
                        new
                        {
                            Id = 6,
                            Age = 2,
                            ContactNumber = "0300-8538605",
                            FullName = "Hasan",
                            Gender = "Male",
                            MedicalHistory = "History of condition 7"
                        },
                        new
                        {
                            Id = 7,
                            Age = 33,
                            ContactNumber = "0300-4388521",
                            FullName = "Husain",
                            Gender = "Male",
                            MedicalHistory = "History of condition 8"
                        },
                        new
                        {
                            Id = 8,
                            Age = 56,
                            ContactNumber = "0300-8039587",
                            FullName = "Zaid",
                            Gender = "Male",
                            MedicalHistory = "History of condition 9"
                        },
                        new
                        {
                            Id = 9,
                            Age = 28,
                            ContactNumber = "0300-6354637",
                            FullName = "Bilal",
                            Gender = "Male",
                            MedicalHistory = "History of condition 10"
                        },
                        new
                        {
                            Id = 10,
                            Age = 81,
                            ContactNumber = "0300-6277229",
                            FullName = "Hamza",
                            Gender = "Male",
                            MedicalHistory = "History of condition 11"
                        },
                        new
                        {
                            Id = 11,
                            Age = 89,
                            ContactNumber = "0300-6473819",
                            FullName = "Khalid",
                            Gender = "Male",
                            MedicalHistory = "History of condition 12"
                        },
                        new
                        {
                            Id = 12,
                            Age = 44,
                            ContactNumber = "0300-6350091",
                            FullName = "Yasir",
                            Gender = "Male",
                            MedicalHistory = "History of condition 13"
                        },
                        new
                        {
                            Id = 13,
                            Age = 8,
                            ContactNumber = "0300-9185307",
                            FullName = "Salman",
                            Gender = "Male",
                            MedicalHistory = "History of condition 14"
                        },
                        new
                        {
                            Id = 14,
                            Age = 86,
                            ContactNumber = "0300-9791846",
                            FullName = "Ibrahim",
                            Gender = "Male",
                            MedicalHistory = "History of condition 15"
                        },
                        new
                        {
                            Id = 15,
                            Age = 34,
                            ContactNumber = "0300-1916861",
                            FullName = "Ismail",
                            Gender = "Male",
                            MedicalHistory = "History of condition 16"
                        },
                        new
                        {
                            Id = 16,
                            Age = 62,
                            ContactNumber = "0300-4966110",
                            FullName = "Yusuf",
                            Gender = "Male",
                            MedicalHistory = "History of condition 17"
                        },
                        new
                        {
                            Id = 17,
                            Age = 86,
                            ContactNumber = "0300-4458671",
                            FullName = "Musa",
                            Gender = "Male",
                            MedicalHistory = "History of condition 18"
                        },
                        new
                        {
                            Id = 18,
                            Age = 40,
                            ContactNumber = "0300-4534086",
                            FullName = "Isa",
                            Gender = "Male",
                            MedicalHistory = "History of condition 19"
                        },
                        new
                        {
                            Id = 19,
                            Age = 28,
                            ContactNumber = "0300-2460738",
                            FullName = "Yunus",
                            Gender = "Male",
                            MedicalHistory = "History of condition 20"
                        },
                        new
                        {
                            Id = 20,
                            Age = 77,
                            ContactNumber = "0300-7279956",
                            FullName = "Yahya",
                            Gender = "Male",
                            MedicalHistory = "History of condition 21"
                        },
                        new
                        {
                            Id = 21,
                            Age = 30,
                            ContactNumber = "0300-2407019",
                            FullName = "Zakariya",
                            Gender = "Male",
                            MedicalHistory = "History of condition 22"
                        },
                        new
                        {
                            Id = 22,
                            Age = 25,
                            ContactNumber = "0300-9283985",
                            FullName = "Sulaiman",
                            Gender = "Male",
                            MedicalHistory = "History of condition 23"
                        },
                        new
                        {
                            Id = 23,
                            Age = 34,
                            ContactNumber = "0300-4694253",
                            FullName = "Dawood",
                            Gender = "Male",
                            MedicalHistory = "History of condition 24"
                        },
                        new
                        {
                            Id = 24,
                            Age = 65,
                            ContactNumber = "0300-1159237",
                            FullName = "Ayub",
                            Gender = "Male",
                            MedicalHistory = "History of condition 25"
                        },
                        new
                        {
                            Id = 25,
                            Age = 14,
                            ContactNumber = "0300-4554590",
                            FullName = "Idris",
                            Gender = "Male",
                            MedicalHistory = "History of condition 26"
                        },
                        new
                        {
                            Id = 26,
                            Age = 57,
                            ContactNumber = "0300-4002335",
                            FullName = "Nuh",
                            Gender = "Male",
                            MedicalHistory = "History of condition 27"
                        },
                        new
                        {
                            Id = 27,
                            Age = 48,
                            ContactNumber = "0300-2016954",
                            FullName = "Adam",
                            Gender = "Male",
                            MedicalHistory = "History of condition 28"
                        },
                        new
                        {
                            Id = 28,
                            Age = 41,
                            ContactNumber = "0300-5394652",
                            FullName = "Salih",
                            Gender = "Male",
                            MedicalHistory = "History of condition 29"
                        },
                        new
                        {
                            Id = 29,
                            Age = 13,
                            ContactNumber = "0300-6032680",
                            FullName = "Imran",
                            Gender = "Male",
                            MedicalHistory = "History of condition 30"
                        },
                        new
                        {
                            Id = 30,
                            Age = 25,
                            ContactNumber = "0300-3704459",
                            FullName = "Usman",
                            Gender = "Male",
                            MedicalHistory = "History of condition 31"
                        },
                        new
                        {
                            Id = 31,
                            Age = 64,
                            ContactNumber = "0300-8342998",
                            FullName = "Abu Bakr",
                            Gender = "Male",
                            MedicalHistory = "History of condition 32"
                        },
                        new
                        {
                            Id = 32,
                            Age = 67,
                            ContactNumber = "0300-1945248",
                            FullName = "Rashed",
                            Gender = "Male",
                            MedicalHistory = "History of condition 33"
                        },
                        new
                        {
                            Id = 33,
                            Age = 13,
                            ContactNumber = "0300-8116753",
                            FullName = "Faisal",
                            Gender = "Male",
                            MedicalHistory = "History of condition 34"
                        },
                        new
                        {
                            Id = 34,
                            Age = 38,
                            ContactNumber = "0300-6686123",
                            FullName = "Majid",
                            Gender = "Male",
                            MedicalHistory = "History of condition 35"
                        },
                        new
                        {
                            Id = 35,
                            Age = 31,
                            ContactNumber = "0300-9716069",
                            FullName = "Fahad",
                            Gender = "Male",
                            MedicalHistory = "History of condition 36"
                        },
                        new
                        {
                            Id = 36,
                            Age = 26,
                            ContactNumber = "0300-5193691",
                            FullName = "Saad",
                            Gender = "Male",
                            MedicalHistory = "History of condition 37"
                        },
                        new
                        {
                            Id = 37,
                            Age = 65,
                            ContactNumber = "0300-6530682",
                            FullName = "Saeed",
                            Gender = "Male",
                            MedicalHistory = "History of condition 38"
                        },
                        new
                        {
                            Id = 38,
                            Age = 25,
                            ContactNumber = "0300-7770003",
                            FullName = "Karim",
                            Gender = "Male",
                            MedicalHistory = "History of condition 39"
                        },
                        new
                        {
                            Id = 39,
                            Age = 28,
                            ContactNumber = "0300-1709603",
                            FullName = "Rahim",
                            Gender = "Male",
                            MedicalHistory = "History of condition 40"
                        },
                        new
                        {
                            Id = 40,
                            Age = 48,
                            ContactNumber = "0300-1655380",
                            FullName = "Rahman",
                            Gender = "Male",
                            MedicalHistory = "History of condition 41"
                        },
                        new
                        {
                            Id = 41,
                            Age = 22,
                            ContactNumber = "0300-1641111",
                            FullName = "Amin",
                            Gender = "Male",
                            MedicalHistory = "History of condition 42"
                        },
                        new
                        {
                            Id = 42,
                            Age = 85,
                            ContactNumber = "0300-6136400",
                            FullName = "Jamil",
                            Gender = "Male",
                            MedicalHistory = "History of condition 43"
                        },
                        new
                        {
                            Id = 43,
                            Age = 72,
                            ContactNumber = "0300-1390702",
                            FullName = "Jalal",
                            Gender = "Male",
                            MedicalHistory = "History of condition 44"
                        },
                        new
                        {
                            Id = 44,
                            Age = 77,
                            ContactNumber = "0300-6237976",
                            FullName = "Jamal",
                            Gender = "Male",
                            MedicalHistory = "History of condition 45"
                        },
                        new
                        {
                            Id = 45,
                            Age = 84,
                            ContactNumber = "0300-5217397",
                            FullName = "Kamal",
                            Gender = "Male",
                            MedicalHistory = "History of condition 46"
                        },
                        new
                        {
                            Id = 46,
                            Age = 3,
                            ContactNumber = "0300-8950639",
                            FullName = "Malik",
                            Gender = "Male",
                            MedicalHistory = "History of condition 47"
                        },
                        new
                        {
                            Id = 47,
                            Age = 38,
                            ContactNumber = "0300-1106954",
                            FullName = "Nabil",
                            Gender = "Male",
                            MedicalHistory = "History of condition 48"
                        },
                        new
                        {
                            Id = 48,
                            Age = 40,
                            ContactNumber = "0300-1422358",
                            FullName = "Nasir",
                            Gender = "Male",
                            MedicalHistory = "History of condition 49"
                        },
                        new
                        {
                            Id = 49,
                            Age = 16,
                            ContactNumber = "0300-3019843",
                            FullName = "Qasim",
                            Gender = "Male",
                            MedicalHistory = "History of condition 50"
                        },
                        new
                        {
                            Id = 50,
                            Age = 24,
                            ContactNumber = "0300-5402258",
                            FullName = "Rafiq",
                            Gender = "Male",
                            MedicalHistory = "History of condition 51"
                        },
                        new
                        {
                            Id = 51,
                            Age = 54,
                            ContactNumber = "0300-7703340",
                            FullName = "Fatima",
                            Gender = "Female",
                            MedicalHistory = "History of condition 52"
                        },
                        new
                        {
                            Id = 52,
                            Age = 5,
                            ContactNumber = "0300-7852392",
                            FullName = "Khadija",
                            Gender = "Female",
                            MedicalHistory = "History of condition 53"
                        },
                        new
                        {
                            Id = 53,
                            Age = 5,
                            ContactNumber = "0300-7186339",
                            FullName = "Aisha",
                            Gender = "Female",
                            MedicalHistory = "History of condition 54"
                        },
                        new
                        {
                            Id = 54,
                            Age = 35,
                            ContactNumber = "0300-1160763",
                            FullName = "Maryam",
                            Gender = "Female",
                            MedicalHistory = "History of condition 55"
                        },
                        new
                        {
                            Id = 55,
                            Age = 19,
                            ContactNumber = "0300-7985097",
                            FullName = "Zainab",
                            Gender = "Female",
                            MedicalHistory = "History of condition 56"
                        },
                        new
                        {
                            Id = 56,
                            Age = 22,
                            ContactNumber = "0300-4373757",
                            FullName = "Ruqayyah",
                            Gender = "Female",
                            MedicalHistory = "History of condition 57"
                        },
                        new
                        {
                            Id = 57,
                            Age = 69,
                            ContactNumber = "0300-1590081",
                            FullName = "Umm Kulthum",
                            Gender = "Female",
                            MedicalHistory = "History of condition 58"
                        },
                        new
                        {
                            Id = 58,
                            Age = 51,
                            ContactNumber = "0300-2804766",
                            FullName = "Hafsa",
                            Gender = "Female",
                            MedicalHistory = "History of condition 59"
                        },
                        new
                        {
                            Id = 59,
                            Age = 14,
                            ContactNumber = "0300-2269435",
                            FullName = "Safiyya",
                            Gender = "Female",
                            MedicalHistory = "History of condition 60"
                        },
                        new
                        {
                            Id = 60,
                            Age = 88,
                            ContactNumber = "0300-7337737",
                            FullName = "Maimuna",
                            Gender = "Female",
                            MedicalHistory = "History of condition 61"
                        },
                        new
                        {
                            Id = 61,
                            Age = 70,
                            ContactNumber = "0300-6045696",
                            FullName = "Juwayriya",
                            Gender = "Female",
                            MedicalHistory = "History of condition 62"
                        },
                        new
                        {
                            Id = 62,
                            Age = 3,
                            ContactNumber = "0300-9559072",
                            FullName = "Asma",
                            Gender = "Female",
                            MedicalHistory = "History of condition 63"
                        },
                        new
                        {
                            Id = 63,
                            Age = 40,
                            ContactNumber = "0300-5105624",
                            FullName = "Hind",
                            Gender = "Female",
                            MedicalHistory = "History of condition 64"
                        },
                        new
                        {
                            Id = 64,
                            Age = 17,
                            ContactNumber = "0300-3436268",
                            FullName = "Salma",
                            Gender = "Female",
                            MedicalHistory = "History of condition 65"
                        },
                        new
                        {
                            Id = 65,
                            Age = 28,
                            ContactNumber = "0300-7089512",
                            FullName = "Hawa",
                            Gender = "Female",
                            MedicalHistory = "History of condition 66"
                        },
                        new
                        {
                            Id = 66,
                            Age = 81,
                            ContactNumber = "0300-1488884",
                            FullName = "Sara",
                            Gender = "Female",
                            MedicalHistory = "History of condition 67"
                        },
                        new
                        {
                            Id = 67,
                            Age = 72,
                            ContactNumber = "0300-8428820",
                            FullName = "Hajar",
                            Gender = "Female",
                            MedicalHistory = "History of condition 68"
                        },
                        new
                        {
                            Id = 68,
                            Age = 43,
                            ContactNumber = "0300-8092501",
                            FullName = "Rahma",
                            Gender = "Female",
                            MedicalHistory = "History of condition 69"
                        },
                        new
                        {
                            Id = 69,
                            Age = 46,
                            ContactNumber = "0300-5370989",
                            FullName = "Amina",
                            Gender = "Female",
                            MedicalHistory = "History of condition 70"
                        },
                        new
                        {
                            Id = 70,
                            Age = 89,
                            ContactNumber = "0300-3350490",
                            FullName = "Halima",
                            Gender = "Female",
                            MedicalHistory = "History of condition 71"
                        },
                        new
                        {
                            Id = 71,
                            Age = 18,
                            ContactNumber = "0300-8113899",
                            FullName = "Nadia",
                            Gender = "Female",
                            MedicalHistory = "History of condition 72"
                        },
                        new
                        {
                            Id = 72,
                            Age = 24,
                            ContactNumber = "0300-1718470",
                            FullName = "Laila",
                            Gender = "Female",
                            MedicalHistory = "History of condition 73"
                        },
                        new
                        {
                            Id = 73,
                            Age = 57,
                            ContactNumber = "0300-6076967",
                            FullName = "Yasmin",
                            Gender = "Female",
                            MedicalHistory = "History of condition 74"
                        },
                        new
                        {
                            Id = 74,
                            Age = 22,
                            ContactNumber = "0300-9625193",
                            FullName = "Farah",
                            Gender = "Female",
                            MedicalHistory = "History of condition 75"
                        },
                        new
                        {
                            Id = 75,
                            Age = 43,
                            ContactNumber = "0300-3029311",
                            FullName = "Noor",
                            Gender = "Female",
                            MedicalHistory = "History of condition 76"
                        },
                        new
                        {
                            Id = 76,
                            Age = 7,
                            ContactNumber = "0300-3731746",
                            FullName = "Sana",
                            Gender = "Female",
                            MedicalHistory = "History of condition 77"
                        },
                        new
                        {
                            Id = 77,
                            Age = 46,
                            ContactNumber = "0300-5217806",
                            FullName = "Zara",
                            Gender = "Female",
                            MedicalHistory = "History of condition 78"
                        },
                        new
                        {
                            Id = 78,
                            Age = 87,
                            ContactNumber = "0300-7364882",
                            FullName = "Huda",
                            Gender = "Female",
                            MedicalHistory = "History of condition 79"
                        },
                        new
                        {
                            Id = 79,
                            Age = 66,
                            ContactNumber = "0300-6823691",
                            FullName = "Maha",
                            Gender = "Female",
                            MedicalHistory = "History of condition 80"
                        },
                        new
                        {
                            Id = 80,
                            Age = 22,
                            ContactNumber = "0300-6392699",
                            FullName = "Rania",
                            Gender = "Female",
                            MedicalHistory = "History of condition 81"
                        },
                        new
                        {
                            Id = 81,
                            Age = 74,
                            ContactNumber = "0300-8022842",
                            FullName = "Salwa",
                            Gender = "Female",
                            MedicalHistory = "History of condition 82"
                        },
                        new
                        {
                            Id = 82,
                            Age = 42,
                            ContactNumber = "0300-7415568",
                            FullName = "Mona",
                            Gender = "Female",
                            MedicalHistory = "History of condition 83"
                        },
                        new
                        {
                            Id = 83,
                            Age = 42,
                            ContactNumber = "0300-2397039",
                            FullName = "Safa",
                            Gender = "Female",
                            MedicalHistory = "History of condition 84"
                        },
                        new
                        {
                            Id = 84,
                            Age = 24,
                            ContactNumber = "0300-4772779",
                            FullName = "Samira",
                            Gender = "Female",
                            MedicalHistory = "History of condition 85"
                        },
                        new
                        {
                            Id = 85,
                            Age = 65,
                            ContactNumber = "0300-9816113",
                            FullName = "Tahira",
                            Gender = "Female",
                            MedicalHistory = "History of condition 86"
                        },
                        new
                        {
                            Id = 86,
                            Age = 56,
                            ContactNumber = "0300-1748625",
                            FullName = "Jameela",
                            Gender = "Female",
                            MedicalHistory = "History of condition 87"
                        },
                        new
                        {
                            Id = 87,
                            Age = 64,
                            ContactNumber = "0300-9057926",
                            FullName = "Nabila",
                            Gender = "Female",
                            MedicalHistory = "History of condition 88"
                        },
                        new
                        {
                            Id = 88,
                            Age = 33,
                            ContactNumber = "0300-2728189",
                            FullName = "Nasira",
                            Gender = "Female",
                            MedicalHistory = "History of condition 89"
                        },
                        new
                        {
                            Id = 89,
                            Age = 62,
                            ContactNumber = "0300-7264084",
                            FullName = "Qadira",
                            Gender = "Female",
                            MedicalHistory = "History of condition 90"
                        },
                        new
                        {
                            Id = 90,
                            Age = 73,
                            ContactNumber = "0300-5188375",
                            FullName = "Rafiqa",
                            Gender = "Female",
                            MedicalHistory = "History of condition 91"
                        },
                        new
                        {
                            Id = 91,
                            Age = 3,
                            ContactNumber = "0300-5353220",
                            FullName = "Malika",
                            Gender = "Female",
                            MedicalHistory = "History of condition 92"
                        },
                        new
                        {
                            Id = 92,
                            Age = 18,
                            ContactNumber = "0300-9667291",
                            FullName = "Kamila",
                            Gender = "Female",
                            MedicalHistory = "History of condition 93"
                        },
                        new
                        {
                            Id = 93,
                            Age = 88,
                            ContactNumber = "0300-1037074",
                            FullName = "Latifa",
                            Gender = "Female",
                            MedicalHistory = "History of condition 94"
                        },
                        new
                        {
                            Id = 94,
                            Age = 29,
                            ContactNumber = "0300-4936251",
                            FullName = "Karima",
                            Gender = "Female",
                            MedicalHistory = "History of condition 95"
                        },
                        new
                        {
                            Id = 95,
                            Age = 73,
                            ContactNumber = "0300-1879918",
                            FullName = "Jalila",
                            Gender = "Female",
                            MedicalHistory = "History of condition 96"
                        },
                        new
                        {
                            Id = 96,
                            Age = 68,
                            ContactNumber = "0300-8434651",
                            FullName = "Marwa",
                            Gender = "Female",
                            MedicalHistory = "History of condition 97"
                        },
                        new
                        {
                            Id = 97,
                            Age = 2,
                            ContactNumber = "0300-9245375",
                            FullName = "Amani",
                            Gender = "Female",
                            MedicalHistory = "History of condition 98"
                        },
                        new
                        {
                            Id = 98,
                            Age = 86,
                            ContactNumber = "0300-2908746",
                            FullName = "Amira",
                            Gender = "Female",
                            MedicalHistory = "History of condition 99"
                        },
                        new
                        {
                            Id = 99,
                            Age = 55,
                            ContactNumber = "0300-5317325",
                            FullName = "Bushra",
                            Gender = "Female",
                            MedicalHistory = "History of condition 100"
                        },
                        new
                        {
                            Id = 100,
                            Age = 9,
                            ContactNumber = "0300-1934433",
                            FullName = "Dalia",
                            Gender = "Female",
                            MedicalHistory = "History of condition 101"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MediCoreHospital.Models.Admission", b =>
                {
                    b.HasOne("MediCoreHospital.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediCoreHospital.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
